version: '3'

services:
    php-fpm:
        build:
            context: ./docker/php
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
                WWWUSER: '${WWWUSER}'
        image: symfony-users/php-fpm
        container_name: symfony-users-php
        environment:
            APP_ENV: ${APP_ENV}
            APP_SECRET: ${APP_SECRET}
            DATABASE_URL: ${DATABASE_URL}
        volumes:
            - ./:/var/www
        networks:
            - users-app-network
        depends_on:
            - database-mysql
            - database-pgsql

    nginx:
        build:
            context: ./docker/nginx
        image: symfony-users/nginx
        container_name: symfony-users-nginx
        volumes:
            - ./:/var/www
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/sites/:/etc/nginx/sites-available
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d
            - ./docker/logs:/var/log
        depends_on:
            - php-fpm
        ports:
            - '${APP_PORT:-80}:80'
        networks:
            - users-app-network

    database-mysql:
        build:
            context: ./docker/database/mysql
        image: symfony-users/database-mysql
        container_name: symfony-users-mysql
        environment:
            - MYSQL_DATABASE=${DATABASE_NAME}
            - MYSQL_USER=${DATABASE_USER}
            - MYSQL_PASSWORD=${DATABASE_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - ./docker/database/mysql/data:/var/lib/mysql
        networks:
            - users-app-network

    database-pgsql:
        build:
            context: ./docker/database/pgsql
        image: symfony-users/database-pgsql
        container_name: symfony-users-pgsql
        environment:
            - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
            - POSTGRES_DB=${DATABASE_NAME}
        ports:
            - "5432:5432"
        volumes:
            - ./docker/database/pgsql/data:/var/lib/postgresql/data
        networks:
            - users-app-network

networks:
    users-app-network:
        driver: bridge
